fixtures:                                                                                                                                                                                                            
  forge_modules:
    stdlib: "puppetlabs/stdlib"
  symlinks:                                                                                                                                                                                                          
    zipfile: "#{source_dir}"
